// Optional DOM behavior test using synthetic responses; not browser visual QA.
// Usage: node scripts/check-ui.mjs /absolute/path/to/jsdom/lib/api.js
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {normalize,success,emptyState} from '../public/core.mjs';
if(!process.argv[2])throw new Error('Pass the installed jsdom module path.');
const {JSDOM}=await import(pathToFileURL(process.argv[2]));
const dom=new JSDOM(await readFile('public/verify.html','utf8'),{url:'https://example.test'});
globalThis.MutationObserver=dom.window.MutationObserver;
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.localStorage=dom.window.localStorage;
const now=new Date().toISOString(),prev=new Date(Date.parse(now)-86400000).toISOString();
const make=(price,t)=>normalize({symbol:'XAU',currency:'USD',price,updatedAt:t},t);
let sample=success(success(emptyState(),make(3000,prev)),make(3030,now));sample.evidence=sample.daily;sample.mode='live';
let failNetwork=false;const requests=[];
globalThis.fetch=async(url,options)=>{requests.push({url,method:options?.method});if(String(url).startsWith('/api/metals')){const symbol=new URL(url,'https://example.test').searchParams.get('symbol');return Response.json({quote:{symbol,value:symbol==='XAG'?60:3030,source_at:now,fetched_at:now}});}if(failNetwork)throw new TypeError('Synthetic disconnect');return new Response(JSON.stringify(sample));};
let tick;
globalThis.setInterval=fn=>{tick=fn;return 0;};
await import('../public/verify.mjs');
await new Promise(r=>setImmediate(r));
const $=id=>document.getElementById(id);
assert.equal($('price').textContent,'3,030.00');assert.equal($('daily-rows').children.length,2);assert.ok($('two-days').textContent.includes('2/2'));
assert.ok($('change').textContent.includes('+30.000000'));
assert.equal(document.querySelector('[id^="news-"]'),null);
assert.equal(requests.length,1);assert.equal(requests[0].method,'GET');
assert.equal(document.querySelectorAll('#asset-inventory tr').length,4);
assert.ok(!document.body.textContent.includes('백금'));assert.ok(!document.body.textContent.includes('팔라듐'));assert.ok(!document.body.textContent.includes('레늄'));
assert.equal(document.querySelector('.quote'),null);assert.equal(document.querySelector('#asset-tabs'),null);
assert.match($('board-title').textContent,/금 기록 대조/);
$('reload-records').click();await new Promise(r=>setImmediate(r));assert.equal(requests.at(-1).method,'GET');
const beforeLab=requests.length;
$('tab-lab').click();assert.equal($('lab').hidden,false);assert.equal($('export').disabled,true);
$('suite').click();
await new Promise(r=>setTimeout(r,250));
assert.equal($('suite-result').children.length,5);assert.ok([...$('suite-result').children].every(x=>x.textContent.startsWith('통과')));
assert.equal($('daily-rows').children.length,2);assert.equal($('price').textContent,'3,040.00');
assert.equal(requests.length,beforeLab);$('tab-live').click();assert.equal($('price').textContent,'3,030.00');
failNetwork=true;$('refresh').click();await new Promise(r=>setImmediate(r));
assert.equal($('price').textContent,'3,030.00');assert.ok($('status').textContent.includes('stale'));assert.equal($('export').disabled,true);
assert.equal(requests.at(-1).method,'POST');const beforeTick=requests.length;tick();assert.equal(requests.length,beforeTick);
console.log('DOM PASS: live rendering, exact fields, daily rows, comparison, 5-failure suite, lab isolation, offline price retention and export guard.');
dom.window.dispatchEvent(new dom.window.Event('pagehide'));
dom.window.close();
